apiVersion: apps/v1
kind: ReplicaSet
metadata: # リソースを一意に特定するための情報
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec: # ReplicaSetの望ましい状態を定義
  replicas: 3 # Podの数
  selector: # .spec.template.metadata.labelsと一致させる。ReplicaSetが所有するPodを指定するため。（今回の場合、tier: frontendが一致している）
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template: # template以下はPodの定義と同様に書く。templateの定義を持つPodの複製を行う。
    metadata:
      labels: # spec.selectorと一致させる（2つのラベルのうちtier: frontendが一致している）
        app: guestbook
        tier: frontend
    spec: # Podの望ましい状態を定義
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 80
        
