apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:  # The list of ports that are exposed by this service.
  - port: 80 # The port that will be exposed by this service.
    targetPort: 8080 # ターゲットとなるPodのポート番号
    protocol: TCP # 
  selector:
    app: echoserver #　このラベルと一致するPodがserviceのターゲットとなり、serviceを経由してtcpリクエストが流れる 
